print("this sohail taking a python course")
print("i want to print a ten line of code")
print("and aslo i ant to print a int with plus function")
print(45*3)
print("i want to became a Data Science engineer")
print("i am setting in my relatives house")
print("thay give me a room for staying house")
print("i am in lahore for finding a job")
print("i am using chatgpt for programing issues and finding errors")
print("chat gpt are awosome")